name: Build and deploy scoring bank

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clon the code
      uses: actions/checkout@v3

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker hub connection
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name:  build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: siriusthier/scoring_bank:latest
