
name: Build and deploy scoring bank

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/scoring_bank:${IMAGE_TAG} .

      # Étape 4 : Pousser l'image Docker vers Docker Hub
      - name: Push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/scoring_bank:${IMAGE_TAG}





